/**
 * @date 8/28/21 - 3:42:48 PM
 *
 * @export
 * @enum {number}
 */

export enum GuildFeatures {
	ANIMATED_ICON = 'ANIMATED_ICON',
	BANNER = 'BANNER',
	COMMERCE = 'COMMERCE',
	COMMUNITY = 'COMMUNITY',
	DISCOVERABLE = 'DISCOVERABLE',
	FEATURABLE = 'FEATURABLE',
	INVITE_SPLASH = 'INVITE_SPLASH',
	MEMBER_VERIFICATION_GATE_ENABLED = 'MEMBER_VERIFICATION_GATE_ENABLED',
	NEWS = 'NEWS',
	PARTNERED = 'PARTNERED',
	PREVIEW_ENABLED = 'PREVIEW_ENABLED',
	VANITY_URL = 'VANITY_URL',
	VERIFIED = 'VERIFIED',
	VIP_REGIONS = 'VIP_REGIONS',
	WELCOME_SCREEN_ENABLED = 'WELCOME_SCREEN_ENABLED',
	TICKETED_EVENTS_ENABLED = 'TICKETED_EVENTS_ENABLED',
	MONETIZATION_ENABLED = 'MONETIZATION_ENABLED',
	MORE_STICKERS = 'MORE_STICKERS',
	THREE_DAY_THREAD_ARCHIVE = 'THREE_DAY_THREAD_ARCHIVE',
	SEVEN_DAY_THREAD_ARCHIVE = 'SEVEN_DAY_THREAD_ARCHIVE',
	PRIVATE_THREADS = 'PRIVATE_THREADS',
}

export enum VerificationLevel {
	NONE = 0,
	LOW = 1,
	MEDIUM = 2,
	HIGH = 3,
	VERY_HIGH = 4,
}

export enum DefaultMessageNotificationsLevel {
	ALL_MESSAGES = 0,
	ONLY_MENTIONS = 1,
}

export enum ExplicitContentFilterLevel {
	DISABLED = 0,
	MEMBERS_WITHOUT_ROLES = 1,
	ALL_MEMBERS = 2,
}

export enum SystemChannelFlags {
	SUPPRESS_JOIN_NOTIFICATIONS = 1 << 0,
	SUPPRESS_PREMIUM_SUBSCRIPTIONS = 1 << 1,
	SUPPRESS_GUILD_REMINDER_NOTIFICATIONS = 1 << 2,
}

export enum MFALevel {
	NONE = 0,
	ELEVATED = 1,
}
